# this file is for harvesting radius pattern (the original file was generated by sortAndMergeRadiusPattern.sh)
if [ "$1" == "" ] || [ "$2" == "" ] || [ "$3" == "" ]; then
	echo ".harvestRadiusPattern.sh patternFile total_threshold win_threshold (-1 means igonre)"
	exit 0
fi

echo "start harvesting radius pattern with count>=$2 or win>=$3"
awk -v count=$2 -v win=$3 -F "\t" '
{
	if( (count!=-1 && $3>=count) || (win!=-1 && $4>=win) ) {
		print $1 "\t" $2 "\t" $3 "\t" $4 "\t" $5
	}
}' $1 > ${1%.*}_harvest.txt
