# this file is for sort and merge radius pattern (the original file was generated by CGI train mode)
if [ "$1" == "" ]; then
	echo "./sortAndMergeRadiusPattern.sh patternFile sort_thread(default is 2)"
	exit 0
fi

sort_thread=2
if [ "$2" != "" ]; then
	sort_thread=$2
fi

echo "start sorting radius pattern, using $sort_thread thread(s) to sort"
sort -k 1,1n -k 2,2 -k 3,3n -k 4,4n -T /tmp --parallel=$sort_thread "$1" -o "$1"

# following is for merge radius pattern count
echo "start merging radius pattern"
awk -F "\t" '
BEGIN {
	radius = hash_key = total = win = 0;
	isFirst = 1;
}
{
	if( isFirst==0 && radius==$1 && hash_key==$2 ) {
		total += $3;
		win += $4;
	} else {
		if( isFirst==1 ) { isFirst = 0; }
		else { print radius "\t" hash_key "\t" total "\t" win "\t" message; }
		radius = $1;
		hash_key = $2;
		total = $3;
		win = $4;
		message = $5;
	}
}
END {
	# for last one
	print radius "\t" hash_key "\t" total "\t" win "\t" message;
}' $1 > $1"_tmp" && mv $1"_tmp" $1
